## 프로그래머스 - LV4 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C
ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC

## 프로그래머스 - LV4 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE) AS PRICE
                          FROM FOOD_PRODUCT
                          WHERE CATEGORY IN ('국', '김치', '식용유', '과자')
                          GROUP BY CATEGORY)
ORDER BY MAX_PRICE DESC

## 프로그래머스 - LV4 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT DATE_FORMAT(B.SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(B.SALES_DATE, '%m') AS MONTH,
       A.GENDER,
       COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, A.GENDER
HAVING A.GENDER IS NOT NULL
ORDER BY YEAR ASC, MONTH ASC, A.GENDER ASC

## 프로그래머스 - LV4 입양 시각 구하기(2)
SET @HOUR = -1;
SELECT (@HOUR := @HOUR +1) AS HOUR,
    (SELECT COUNT(ANIMAL_ID)
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23;

## 프로그래머스 - LV4 언어별 개발자 분류하기
SELECT CASE WHEN GROUP_CONCAT(B.NAME) LIKE '%Python%' AND GROUP_CONCAT(B.CATEGORY) LIKE '%Front%' THEN 'A'
WHEN GROUP_CONCAT(B.NAME) LIKE '%C#%' THEN 'B'
WHEN GROUP_CONCAT(B.CATEGORY) LIKE '%Front%' THEN 'C' END 'GRADE',
A.ID, A.EMAIL
FROM DEVELOPERS A
JOIN SKILLCODES B
ON A.SKILL_CODE & B.CODE
GROUP BY A.ID, A.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, A.ID